/**
 * Navbar height is h-16 = 64px. Headings have scroll-m-20 = 80px scroll-margin.
 * The reading line is placed at 80px from viewport top so that clicking a TOC
 * link (which scrolls the heading to 80px) and scroll-based activation stay
 * perfectly in sync.
 */
export const READING_LINE_OFFSET = 80;

/** Bottom margin kept below the expanded reading line at max scroll. */
const BOTTOM_MARGIN = 50;

export const APP_SCROLL_CONTAINER_ID = "app-scroll-container";

export interface ScrollRootMetrics {
  scrollTop: number;
  viewportHeight: number;
  scrollHeight: number;
  rootTop: number;
}

/** Strip the leading `#` from a TOC href to get the element ID. */
export function hrefToId(href: string): string {
  return href.startsWith("#") ? href.slice(1) : href;
}

export function getAppScrollContainer(): HTMLElement | null {
  return document.getElementById(APP_SCROLL_CONTAINER_ID);
}

function isWindowScrollRoot(
  scrollRoot: HTMLElement | Window
): scrollRoot is Window {
  return typeof Window !== "undefined" && scrollRoot instanceof Window;
}

export function getScrollRootMetrics(
  scrollRoot: HTMLElement | Window
): ScrollRootMetrics {
  if (isWindowScrollRoot(scrollRoot)) {
    return {
      scrollTop: window.scrollY,
      viewportHeight: window.innerHeight,
      scrollHeight: document.documentElement.scrollHeight,
      rootTop: 0,
    };
  }

  return {
    scrollTop: scrollRoot.scrollTop,
    viewportHeight: scrollRoot.clientHeight,
    scrollHeight: scrollRoot.scrollHeight,
    rootTop: scrollRoot.getBoundingClientRect().top,
  };
}

/**
 * Resolve TOC ids to actual DOM heading elements.
 * Falls back to querying `<article>` headings directly when the
 * computed slugs don't match the IDs generated by rehype-slug.
 */
export function findHeadingElements(tocIds: string[]): HTMLElement[] {
  const byId = tocIds
    .map((id) => document.getElementById(id))
    .filter(Boolean) as HTMLElement[];

  if (byId.length > 0) return byId;

  const article = document.querySelector("article");
  if (!article) return [];
  return Array.from(
    article.querySelectorAll<HTMLElement>("h2[id], h3[id], h4[id]")
  );
}

/**
 * Compute the reading line (absolute document position) that determines
 * which heading is currently "active".
 *
 * Normally it sits at `scrollTop + READING_LINE_OFFSET`. Near the page bottom
 * it progressively expands toward the viewport bottom so that every section
 * — even short ones at the end — gets a proportional activation range.
 */
export function computeReadingLine(
  scrollTop: number,
  viewportHeight: number,
  docHeight: number
): number {
  const maxScrollY = docHeight - viewportHeight;
  const distToBottom = Math.max(0, maxScrollY - scrollTop);

  let readingLine = scrollTop + READING_LINE_OFFSET;

  if (maxScrollY > 0 && distToBottom < viewportHeight) {
    const maxExpansion = Math.max(
      0,
      viewportHeight - READING_LINE_OFFSET - BOTTOM_MARGIN
    );
    const progress = 1 - distToBottom / viewportHeight;
    readingLine += Math.round(progress * maxExpansion);
  }

  return readingLine;
}

/**
 * Find the active heading — the last one whose absolute position is at or
 * above the reading line. Iterates in reverse for efficiency.
 * Returns the element ID, defaulting to the first heading.
 */
export function findActiveHeadingId(
  headings: HTMLElement[],
  readingLine: number,
  metrics: ScrollRootMetrics
): string {
  for (let i = headings.length - 1; i >= 0; i--) {
    const absoluteTop =
      headings[i].getBoundingClientRect().top -
      metrics.rootTop +
      metrics.scrollTop;
    if (absoluteTop <= readingLine) {
      return headings[i].id;
    }
  }
  return headings[0].id;
}
