import { Paths } from "@/src/lib/pageroutes"

// Auto-generated by docs-generator. Do not edit manually.
// Run `pnpm generate:docs` to regenerate.
// Configure in src/contents/settings/docs.config.ts

export const Documents: Paths[] = [
  {
    heading: "Introduction",
    title: "Basic Setup",
    href: "/basic-setup",
    items: [
      {
        title: "Installation",
        href: "/installation",
      },
      {
        title: "Setup",
        href: "/setup",
      },
      {
        title: "Changelog",
        href: "/changelog",
      },
      {
        title: "New mage",
        href: "/new-page",
      },
    ],
  },
  {
    spacer: true,
  },
  {
    heading: "Documents",
    title: "Navigation",
    href: "/navigation",
  },
  {
    title: "Structure",
    href: "/structure",
    items: [
      {
        title: "Deep",
        href: "/deep",
        items: [
          {
            title: "Deeper",
            href: "/deeper",
            items: [
              {
                title: "Even deeper",
                href: "/even-deeper",
              },
            ],
          },
        ],
      },
    ],
  },
  {
    spacer: true,
  },
  {
    heading: "Components",
    title: "Markdown",
    href: "/markdown",
    items: [
      {
        title: "Cards",
        href: "/cards",
      },
      {
        title: "Diagrams",
        href: "/diagrams",
      },
      {
        title: "Filetree",
        href: "/filetree",
      },
      {
        title: "Lists",
        href: "/lists",
      },
      {
        title: "Maths",
        href: "/maths",
      },
      {
        title: "Notes",
        href: "/notes",
      },
      {
        title: "Steps",
        href: "/steps",
      },
      {
        title: "Table",
        href: "/table",
      },
      {
        title: "Tabs",
        href: "/tabs",
      },
    ],
  },
  {
    title: "Random",
    href: "/random",
  },
  {
    title: "Another Page",
    href: "/another-page",
  },
]
